### ISSUE TITLE
Renovate does not update nix lockfile

### ISSUE THREAD

**Issue by brumhard** [SchwarzIT/go-template#193]
### What happened?

Renovate updates update the go.sum file but not the nix lockfile which breaks the nix derivation.
Probably an additional renovate step is required to fix that.

### How can we reproduce this?

-

### gt version

```bash
-
```

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by linuxluigi** [comment]
Could P https://github.com/SchwarzIT/go-template/pull/213 fix it?

**Comment by brumhard** [comment]
Fixed with https://github.com/SchwarzIT/go-template/pull/213
