### ISSUE TITLE
Improve goreleaser config

### ISSUE THREAD

**Issue by brumhard** [SchwarzIT/go-template#57]
We currently only have a minimal goreleaser setup. This could be enriched with the following:
- [ ] better changelogs with github and semantic commits
- [ ] release footer with `gt new`
- [ ] universal_binaries for mac OS
- [x] cosign (#69)
- [ ] brew tap
- [ ] scoop
- [ ] Docker images
- [ ] fury.io to publish linux packages

**Comment by dirien** [comment]
hi @brumhard,

Let me know when to tackle the brew and docker part. We can do this all in goreleaser quite comfortable. Brew if you want your own tap. 

If you want to use the homebrew-core, let me know too. So I can take care of the ruby shizzle there. :) But the we need a GitHub bot to auto create the PR there too for updates. 

With a own tap and gorleaser you would not need this step.

**Comment by brumhard** [comment]
Hi @dirien, thanks for offering your help.
We'll definitely get in touch with you about that and do a little Goreleaser session to close this 👍🏻
I personally think that a SchwarzIT brew tap would be pretty nice, but ofc we can discuss it.

**Comment by MarvinJWendt** [comment]
Good ideas, but since this issue is 3 years old now, I will close it (for now). We are currently re-evaluating the stack that we want to use for the go-template.
