### ISSUE TITLE
Set ZAP loglevel via environment var

### ISSUE THREAD

**Issue by linuxluigi** [SchwarzIT/go-template#82]
### Is your feature request related to a problem? Please describe.

It's useful for 12factor apps.

### Describe the solution you'd like

Set Zap logging level through an environment var.
Example for debug: `LOG_LEVEL=debug`

### Describe alternatives you've considered

...

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by linuxluigi** [comment]
#92

**Comment by brumhard** [comment]
Closed with #92
